### ISSUE TITLE
Implementacion de Modulo Bluetooth para multiples dispositivos compatible con Publish-Subscribe

### ISSUE THREAD

**Issue by GabrielaMQ** [GabrielaMQ/Bluetooth_Game#3]
@lopez12 @asusarrey

**Comment by asusarrey** [comment]
Done, Source Code already uploaded.

Source Code is in Google drive named as Unouag_BT_cnx.rar

**Comment by asusarrey** [comment]
Source Code is in Google drive named as Unouag_BT_cnx.rar
